name: Build and deploy
on:
  push:
    paths: ['src/**']

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1
        with:
          persistent-credentials: false
      - name: Install and build
        run: |
          yarn
          yarn storybook:build
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@3.6.2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: master
          FOLDER: docs # source
          CLEAN: true # remove deleted files
          TARGET_FOLDER: docs # destination/ target
